### ISSUE TITLE
Mismatch between the return type of the checkV2CustomDomain method and its actual returned value

### ISSUE THREAD

**Issue by pfabrikant** [tempmail-lol/api-javascript#3]
**Describe the bug**
The return type of the method is `Promise<Email[] | undefined>
`
The actual returned value is something like
{ email: [{...}] }, so a property that does not exist on the type
**To Reproduce**
call the method and check the actual returned payload

**Expected behavior**
The type and returned value match

**Comment by AlexanderEpolite** [comment]
Fixed in 4.1.0
